apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitalsync-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitalsync-frontend
  template:
    metadata:
      labels:
        app: vitalsync-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mariecrt/vitalsync-frontend:latest
          ports:
            - containerPort: 80
